# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hr_dX51a_7axtAc1dmQJYE1hsGgF7Cm1
"""


import  streamlit as st
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from PIL import Image
import re
import string
import nltk
import spacy

with open("/content/tfidf_vectorizer (2).pkl","rb") as file:
  model = pickle.load(file)

with open("/content/svm_model.pkl",'rb') as file:
  vectorizer =pickle.load(file)
nltk.download('stopwords')
stopwords =nltk.corpus.stopwords.words('english')


def clean_text(text):
    text = text.lower()
    return text.strip()

def remove_punctuation(text):
    punctuation_free = "".join([i for i in text if i not in string.punctuation])
    return punctuation_free

def tokenization(text):
    tokens = re.split(' ', text)
    return tokens

def remove_stopwords(text):
    output = " ".join(i for i in text if i not in stopwords)
    return output

def lemmatizer(text):
    nlp = spacy.load('en_core_web_sm')
    doc = nlp(text)
    sent = [token.lemma_ for token in doc if not token.text in set(stopwords)]
    return ' '.join(sent)

st.title("Sentiment Analysis App")
st.markdown("By KONDETI PAVANI")
image = Image.open("/content/sentiment analysis.png")
st.image(image, use_column_width=True)

